version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: medical-postgres
    environment:
      POSTGRES_DB: medical_db
      POSTGRES_USER: medical_user
      POSTGRES_PASSWORD: medical_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medical_user -d medical_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - medical-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: medical-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medical_db
      SPRING_DATASOURCE_USERNAME: medical_user
      SPRING_DATASOURCE_PASSWORD: medical_password
    depends_on:
      - postgres
    networks:
      - medical-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medical-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - medical-network

  adminer:
    image: adminer
    container_name: medical-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - medical-network

volumes:
  postgres_data:

networks:
  medical-network:
    driver: bridge 