version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: medical-postgres
    environment:
      POSTGRES_DB: medical_db
      POSTGRES_USER: medical_user
      POSTGRES_PASSWORD: medical_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medical_user -d medical_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer
    container_name: medical-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: 