spring:
  application:
    name: medical-backend
  
  datasource:
    url: jdbc:postgresql://dpg-d1dqqlbipnbc73djckq0-a.oregon-postgres.render.com:5432/florism_db
    username: florism_db_user
    password: kZ2vDOaXY9OK8rOw0KXVQy7k3Eel6iNp
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://your-app.render.com}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    com.medicalswp: INFO
    org.hibernate.SQL: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

cors:
  allowed-origins: ${CORS_ORIGINS:https://your-frontend-app.render.com,http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true 