spring:
  application:
    name: medical-backend
  
  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
  
  datasource:
    url: jdbc:postgresql://dpg-d1dqqlbipnbc73djckq0-a.oregon-postgres.render.com:5432/florism_db
    username: ${DB_USERNAME:florism_db_user}
    password: ${DB_PASSWORD:kZ2vDOaXY9OK8rOw0KXVQy7k3Eel6iNp}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Email Configuration
  mail:
    host: ${MAIL_HOST:smtp.hostinger.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:info@florism.site}
    password: ${MAIL_PASSWORD:Sontungmtp!23}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: ${MAIL_HOST:smtp.hostinger.com}
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
        debug: true
    test-connection: false
  
  # Task Scheduling
  task:
    scheduling:
      pool:
        size: 5
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

# App Configuration
app:
  name: ${APP_NAME:Florism Care}
  contact:
    phone: ${CONTACT_PHONE:1900 1234}
    email: ${CONTACT_EMAIL:info@florism.site}
    address: ${CONTACT_ADDRESS:123 Đường ABC, Quận 1, TP.HCM}

logging:
  level:
    com.medicalswp: DEBUG
    com.medicalswp.filter.JwtAuthenticationFilter: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: ${SHOW_SQL:false}
    org.springframework.mail: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:3001}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true 